import { chromium } from "@playwright/test";
const [out, id] = process.argv.slice(2);
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on("pageerror", (e) => console.log("pageerror", String(e).slice(0, 200)));
await page.goto(`http://127.0.0.1:5190/f/${id}?theme=day`, { waitUntil: "load" });
await page.waitForTimeout(4000);
await page.screenshot({ path: `${out}/report-day.png`, fullPage: true });
await page.getByRole("tab", { name: "근거 지도" }).click();
await page.waitForTimeout(4000);
await page.screenshot({ path: `${out}/evmap-day.png`, fullPage: true });
  await page.goto(`http://127.0.0.1:5190/f/${id}?theme=night`, { waitUntil: "load" }); await page.waitForTimeout(3000); await page.getByRole("tab", { name: "근거 지도" }).click(); await page.waitForTimeout(1500); await page.screenshot({ path: `${out}/evmap-night.png` });
await browser.close();
